const GENERATE_SESSION_TOKEN_LENGTH = 60;
const GENERATE_RESET_PASSWORD_TOKEN_LENGTH = 30;
const ENCRYPT_SALT_ROUNDS = 10;

module.exports = {
    GENERATE_SESSION_TOKEN_LENGTH,
    GENERATE_RESET_PASSWORD_TOKEN_LENGTH,
    ENCRYPT_SALT_ROUNDS
};